In [156]:
# ============================================================
# 						PANDAS 실습 문제
# 										2026년 05월 01일
# ============================================================
# [사용 파일]
# - 시도별 전출입 인구수.xlsx 

import pandas as pd

In [157]:
# ============================================================
# 문제 1) 데이터 파일을 읽고 기본 구조를 확인하세요.
# [요구사항]
# 1.  "시도별 전출입 인구수.xlsx" 파일의 "데이터" 시트를 읽어 DataFrame으로 저장하세요.
# 2. 앞부분 5개 행을 출력하세요.
# 3. 데이터의 행수와 열수를 출력하세요.
# 4. 각 컬럼의 자료형을 확인하세요.
# ============================================================
df = pd.read_excel(r'C:\Users\KDT013\14_AI_Data\[2]Pandas\DATA\시도별 전출입 인구수.xlsx', index_col=[0, 1], header=[0, 1])
display(df.head(5))
print(df.shape[0], df.shape[1])
print(df.dtypes)

전입지별         1970     1971     1972     1973     1974     1975     1976  \
         이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명)
전국 전국     4046536  4210164  3687938  4860418  5297969  9011440  6773250
   서울특별시  1742813  1671705  1349333  1831858  2050392  3396662  2756510
   부산광역시   448577   389797   362202   482061   680984   805979   724664
   대구광역시        -        -        -        -        -        -        -
   인천광역시        -        -        -        -        -        -        -

전입지별         1977     1978     1979  ...     2008     2009     2010     2011  \
         이동자수 (명) 이동자수 (명) 이동자수 (명)  ... 이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명)
전국 전국     7397623  8410276  7324380  ...  8808256  8487275  8226594  8127195
   서울특별시  2893403  3307439  2589667  ...  2025358  1873188  1733015  1721748
   부산광역시   785117   895337   809483  ...   514502   519310   519334   508043
   대구광역시        -        -        -  ...   409938   398626   370817   370563
   인천광역시        -        -        -  ...   565585   478169   462051   499567

전입지별         2012     2013     2014     2015     2016     2017
         이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명) 이동자수 (명)
전국 전국     7506691  7411784  7629098  7755286  7378430  7154226
   서울특별시  1555281  1520090  1573594  1589431  1515602  1472937
   부산광역시   461042   478451   485710   507031   459015   439073
   대구광역시   348642   351873   350213   351424   328228   321182
   인천광역시   468666   461613   452297   473223   441646   409465

[5 rows x 48 columns]

324 48
전입지별
1970  이동자수 (명)    object
1971  이동자수 (명)    object
1972  이동자수 (명)    object
1973  이동자수 (명)    object
1974  이동자수 (명)    object
1975  이동자수 (명)    object
1976  이동자수 (명)    object
1977  이동자수 (명)    object
1978  이동자수 (명)    object
1979  이동자수 (명)    object
1980  이동자수 (명)    object
1981  이동자수 (명)    object
1982  이동자수 (명)    object
1983  이동자수 (명)    object
1984  이동자수 (명)    object
1985  이동자수 (명)    object
1986  이동자수 (명)    object
1987  이동자수 (명)    object
1988  이동자수 (명)    object
1989  이동자수 (명)    object
1990  이동자수 (명)    object
1991  이동자수 (명)    object
1992  이동자수 (명)    object
1993  이동자수 (명)    object
1994  이동자수 (명)    object
1995  이동자수 (명)    object
1996  이동자수 (명)    object
1997  이동자수 (명)    object
1998  이동자수 (명)    object
1999  이동자수 (명)    object
2000  이동자수 (명)    object
2001  이동자수 (명)    object
2002  이동자수 (명)    object
2003  이동자수 (명)    object
2004  이동자수 (명)    object
2005  이동자수 (명)    object
2006  이동자수 (명)    object
2007  이동자수 (명)    object
2008  이동자수 (명)    object
2009  이동자수 (명)    object
2010  이동자수 (명)    object
2011  이동자수 (명)    object
2012  이동자수 (명)     int64
2013  이동자수 (명)     int64
2014  이동자수 (명)     int64
2015  이동자수 (명)     int64
2016  이동자수 (명)     int64
2017  이동자수 (명)     int64
dtype: object

In [158]:
# ============================================================
# 문제 2) 불필요한 행을 삭제하고 인덱스를 초기화하세요.
# [요구사항]
# 1. 데이터 파일을 읽은 후, 두 번째 행에 들어 있는 "이동자수 (명)" 설명 행을 삭제하세요.
# 2. 삭제 후 행 인덱스를 0부터 다시 설정하세요.
# 3. 처리 전과 처리 후의 행과 열 수를 각각 출력하세요.
# 4. 처리 후 앞부분 5개 행을 출력하세요.
# ============================================================
df_af = df.copy()
df_af.columns = [col[0] for col in df.columns]
df_af.reset_index(drop=False, level=[0, 1], names=['전출지별', '전입지별'], inplace=True)
print('처리 전 행:', df.shape[0], '개')
print('처리 전 열:', df.shape[1], '개')
print('처리 후 행:', df_af.shape[0], '개')
print('처리 후 열:', df_af.shape[1], '개')
display(df_af.head())

처리 전 행: 324 개
처리 전 열: 48 개
처리 후 행: 324 개
처리 후 열: 50 개

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
1,전국,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
2,전국,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
3,전국,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182
4,전국,인천광역시,-,-,-,-,-,-,-,-,...,565585,478169,462051,499567,468666,461613,452297,473223,441646,409465

In [159]:
# ============================================================
# 문제 3) 연도 컬럼의 자료형을 숫자형으로 변환하세요.
# [요구사항]
# 1. 1970년부터 2017년까지의 연도 컬럼을 선택하세요.
# 2. 연도별 이동자수 데이터에 포함된 "-" 값을 결측치로 처리할 수 있도록 변환하세요.
# 4. 변환 후 연도 컬럼들의 자료형을 출력하세요.
# 5. 전체 결측치 개수를 출력하세요.
# ============================================================
for col in df_af.columns[2:]:
    df_af[col] = pd.to_numeric(df_af[col], downcast='integer', errors='coerce')
display(df_af.dtypes)
print('전체 결측치 개수', df_af.isna().sum().sum(), '개')

전출지별     object
전입지별     object
1970    float64
1971    float64
1972    float64
1973    float64
1974    float64
1975    float64
1976    float64
1977    float64
1978    float64
1979    float64
1980    float64
1981    float64
1982    float64
1983    float64
1984    float64
1985    float64
1986    float64
1987    float64
1988    float64
1989    float64
1990    float64
1991    float64
1992    float64
1993    float64
1994    float64
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012      int32
2013      int32
2014      int32
2015      int32
2016      int32
2017      int32
dtype: object

전체 결측치 개수 3642 개

In [160]:
# ============================================================
# 문제 4) 특정 행과 열을 선택하세요.
# [요구사항]
# 1. 전출지별, 전입지별, 1970, 1980, 1990, 2000, 2010, 2017 컬럼만 선택하여 새로운 DataFrame을 만드세요.
# 2. 앞에서 10개 행만 출력하세요.
# 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
# 4. 0번 행의 2017년 이동자수 값을 선택하여 출력하세요.
# ============================================================
df_new = df_af[['전출지별', '전입지별', 1970, 1980, 1990, 2000, 2010, 2017]]
display(df_new.head(10))
display(df_new[['전출지별', '전입지별', 2017]])
print('2017년 이동자수 값 :', df_new.loc[0, 2017])

,전출지별,전입지별,1970,1980,1990,2000,2010,2017
0,전국,전국,4046536.0,8258573.0,9459209.0,9009441.0,8226594.0,7154226
1,전국,서울특별시,1742813.0,2767816.0,2726492.0,2219407.0,1733015.0,1472937
2,전국,부산광역시,448577.0,904252.0,761684.0,595975.0,519334.0,439073
3,전국,대구광역시,NaN,NaN,526547.0,477595.0,370817.0,321182
4,전국,인천광역시,NaN,NaN,567863.0,531318.0,462051.0,409465
5,전국,광주광역시,NaN,NaN,330810.0,301498.0,268574.0,208138
6,전국,대전광역시,NaN,NaN,296756.0,312560.0,262432.0,211449
7,전국,울산광역시,NaN,NaN,NaN,166690.0,161146.0,135199
8,전국,세종특별자치시,NaN,NaN,NaN,NaN,NaN,82073
9,전국,경기도,452060.0,1085764.0,1609933.0,2042327.0,2168820.0,1888324

        전출지별     전입지별     2017
0         전국       전국  7154226
1         전국    서울특별시  1472937
2         전국    부산광역시   439073
3         전국    대구광역시   321182
4         전국    인천광역시   409465
..       ...      ...      ...
319  제주특별자치도     전라북도      768
320  제주특별자치도     전라남도     1102
321  제주특별자치도     경상북도      994
322  제주특별자치도     경상남도     1501
323  제주특별자치도  제주특별자치도    63275

[324 rows x 3 columns]

2017년 이동자수 값 : 7154226

In [ ]:
# ============================================================
# 문제 5) 서울특별시에서 다른 지역으로 전출한 데이터만 추출하세요.
# ============================================================
# df_new.set_index(['전출지별', '전입지별'], inplace=True)
display(df_new.xs(key='서울특별시', level='전출지별').iloc[2:])

             1970      1980      1990      2000      2010    2017
전입지별
부산광역시     11568.0   29202.0   22005.0   15968.0   17418.0   14484
대구광역시         NaN       NaN   12219.0    9986.0   10277.0    8891
인천광역시         NaN       NaN  103533.0   52829.0   46082.0   40485
광주광역시         NaN       NaN   16416.0   11579.0   11095.0    7932
대전광역시         NaN       NaN   19028.0   16154.0   13819.0   11815
울산광역시         NaN       NaN       NaN    4105.0    4742.0    4260
세종특별자치시       NaN       NaN       NaN       NaN       NaN    5813
경기도      130149.0  297539.0  473889.0  435573.0  410735.0  342433
강원도        9352.0   32858.0   26591.0   22832.0   22736.0   21016
충청북도       6700.0   24548.0   21586.0   14934.0   15461.0   13302
충청남도      15954.0   54480.0   29993.0   23083.0   24522.0   21020
전라북도      10814.0   39396.0   32144.0   22390.0   17569.0   13179
전라남도      10513.0   56251.0   35589.0   22969.0   16429.0   12426
경상북도      11868.0   48839.0   21490.0   14576.0   16042.0   12464
경상남도       8409.0   29205.0   24216.0   11741.0   15689.0   12692
제주특별자치도    1039.0    4828.0    6364.0    5198.0    5714.0   10404

In [ ]:
# ============================================================
# 문제 6)  서울특별시로 전입한 지역의 데이터 추출한 문제입니다
# [요구사항]
# 1. 전출지별이  "부산광역시", "대구광역시", "인천광역시", "경기도"  중 하나인 행만 추출하세요.
# 2. 전입지별, 1990, 2000, 2010, 2017 컬럼만 출력하세요.
# 3. 2017년 이동자수 기준으로 내림차순 정렬하세요.
# ============================================================
display(df_new.xs(key='서울특별시', level='전입지별').loc[["부산광역시", "대구광역시", "인천광역시", "경기도"], ['1990', '2000', '2010', '2017']].sort_values(by='2017', ascending=False))

           1990      2000      2010    2017
전출지별
경기도    282914.0  312616.0  285963.0  234448
인천광역시   43247.0   45970.0   35670.0   32528
부산광역시   34978.0   28564.0   23116.0   19460
대구광역시   19521.0   16970.0   13915.0   13011

In [166]:
# ============================================================
# 문제 7) query()를 사용하여 2017년 이동자수가 100000명 이상인 데이터를 추출하세요.

# [요구사항]
# 1. 연도 컬럼을 숫자형으로 변환한 DataFrame을 사용하세요.
# 2. query()를 사용하여 2017년 이동자수가 100000명 이상인 행을 추출하세요.
# 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
# 4. 2017년 이동자수 기준으로 내림차순 정렬하세요.

# [주의사항]
# - 컬럼명이 숫자 형태이면 query()에서 사용하기 어려울 수 있습니다.
# - 필요한 경우 2017 컬럼명을 "Y2017"과 같이 변경한 후 query()를 사용하세요.
# ============================================================
df_new.columns = df_new.columns.astype(str)
# df_new.query('2017 >= 100000')
display(df_new.head(10))

                   1970       1980       1990       2000       2010     2017
전출지별 전입지별
전국   전국       4046536.0  8258573.0  9459209.0  9009441.0  8226594.0  7154226
     서울특별시    1742813.0  2767816.0  2726492.0  2219407.0  1733015.0  1472937
     부산광역시     448577.0   904252.0   761684.0   595975.0   519334.0   439073
     대구광역시          NaN        NaN   526547.0   477595.0   370817.0   321182
     인천광역시          NaN        NaN   567863.0   531318.0   462051.0   409465
     광주광역시          NaN        NaN   330810.0   301498.0   268574.0   208138
     대전광역시          NaN        NaN   296756.0   312560.0   262432.0   211449
     울산광역시          NaN        NaN        NaN   166690.0   161146.0   135199
     세종특별자치시        NaN        NaN        NaN        NaN        NaN    82073
     경기도       452060.0  1085764.0  1609933.0  2042327.0  2168820.0  1888324

In [ ]:
# ============================================================
# 문제 8) 인덱스를 설정하고 정렬하세요.

# [요구사항]
# 1. 전출지별과 전입지별 컬럼을 행 인덱스로 설정하세요.
# 2. 설정된 인덱스를 기준으로 오름차순 정렬하세요.
# 3. loc을 사용하여 전출지별이 "서울특별시"인 데이터만 선택하세요.
# 4. 선택 결과에서 2017년 이동자수 상위 5개 지역을 출력하세요.

# ============================================================

In [ ]:
# ============================================================
# 문제 9) 기초 통계 값을 확인하세요.

# [요구사항]
# 1. 1970년부터 2017년까지 연도 컬럼만 선택하세요.
# 2. 각 연도별 이동자수 평균값을 구하세요.
# 3. 각 연도별 이동자수 최댓값을 구하세요.
# 4. 2017년 이동자수의 평균, 중앙값, 최댓값, 최솟값, 표준편차를 각각 출력하세요.
# 5. describe()를 사용하여 전체 연도 컬럼의 기술 통계 정보를 출력하세요.
# ============================================================

In [ ]:
# ============================================================
# 문제 10) 행/열을 추가하고 값을 수정하세요.

# [요구사항]
# 1. 전출지별이 "서울특별시"인 데이터만 추출한 후 복사본을 만드세요.
# 2. 2017년 이동자수에서 2010년 이동자수를 뺀 값을 "증감_2010_2017" 컬럼으로 추가하세요.
# 3. "증감_2010_2017" 값이 양수이면 "증가", 0이면 "동일", 음수이면 "감소"로 표시하는 "변화구분" 컬럼을 추가하세요.
# 4. 전입지별이 "서울특별시"인 행의 변화구분 값을 "자기지역"으로 수정하세요.
# 5. 전입지별, 2010, 2017, 증감_2010_2017, 변화구분 컬럼만 출력하세요.
# ============================================================