## [ 데이터 필터링 ]
- DataFrame/Series에서 원하는 데이터만 추출
- 불린인덱싱
- 메서드 isin()
- 메서드 query()

In [2]:
# [1] 모듈 로딩 및 데이터 준비
import pandas as pd

In [ ]:
# [2] 데이터 로딩 및 기본 정보 출력
df = pd.read_excel(r'../DATA/학생관리부.xlsx', header=2)

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
2  이길동   1  7   12
3  박길동   3  1    9
4  최길동   2  1   43

In [11]:
# [3] 특정 조건에 맞는 데이터만 추출 즉, 필터링
# [3-1] 석차가 상위 10위까지만 데이터 추출
# 비교 연산으로 True/False로 구성된 Series
bool_sr = df[df.columns[-1]] <= 10
bool_sr

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [17]:
# 상위 10위 안에 있는 데이터만 추출
df[bool_sr]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
3  박길동   3  1    9

In [18]:
# 상위 10위 밖에 있는 데이터만 추출
# ~ : not 연산자 현재 결과를 반대로
df[~ bool_sr]

    이름  학년  반   석차
2  이길동   1  7   12
4  최길동   2  1   43

In [20]:
# [3-2] 1학년 중 상위 10위 안에 들어가는 학생 데이터
#       => 학년 컬럼 == 1, 석차 <= 10 : 2개 조건 모두 만족
# columns 속성으로 컬럼명 추출
bool_sr1 = df[df.columns[1]] == 1        # 학년 컬럼 == 1
bool_sr2 = df[df.columns[-1]] <= 10      # 석차 컬럼 <= 10

# 1학년이면서 석차가 10위 안에 있는 학생 즉, And 연산 : &
mask_sr = bool_sr1 & bool_sr2
mask_sr

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [21]:
df[mask_sr]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1