#### 【 데이터 연결 】<hr>
- 목적 : 데이터를 방향만 정해서 단순히 이어붙이는 함수

- 기준 : 행 인덱스 또는 컬럼 방향
- 사용 : 같은 구조 즉, 동일 컬럼의 파일을 여러 개 합칠 때 사용
    * 컬럼이 동일하지 않아도 연결은 가능하지만
    * 좋은 concat 데이터는 컬럼 구조가 동일한 데이터

- 메서드 : pandas.concat()
    * 주요 매개변수 : axis, join

[1] 모듈 로딩 및 데이터 준비 <hr>

In [27]:
## 모듈 로딩
import pandas as pd

In [43]:
## 데이터 파일들
FILE1 = '../DATA/stock_price_2024_01.xlsx'
FILE2 = '../DATA/stock_price_2024_02.xlsx'
FILE3 = '../DATA/stock_price_2024_03.xlsx'
FILE4 = '../DATA/stock_price_2024_04.xlsx'

[2] 데이터 로딩 및 기본 정보 확인<hr>

In [44]:
## -----------------------------------
## 데이터 로딩 : 첫번째 행 - 컬럼명 OK
## -----------------------------------
janDF = pd.read_excel(FILE1)
febDF = pd.read_excel(FILE2)
marDF = pd.read_excel(FILE3)
apiDF = pd.read_excel(FILE4)

In [53]:
## -----------------------------------
## 기본 정보 확인
## -----------------------------------
df_list = [janDF, febDF, marDF, apiDF]

for df in df_list:
    print(f'\n=============')
    df.info()
    print(df.columns)

=============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        6 non-null      datetime64[ns]
 1   id          6 non-null      object
 2   stock_name  6 non-null      object
 3   market      6 non-null      object
 4   price       6 non-null      int64
 5   volume      6 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 416.0+ bytes
Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

=============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        6 non-null      datetime64[ns]
 1   id          6 non-null      object
 2   stock_name  6 non-null      object
 3   market      6 non-null      object
 4   price       6 non-null      int64
 5   volume      6 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 416.0+ bytes
Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

=============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        6 non-null      datetime64[ns]
 1   id          6 non-null      object
 2   stock_name  6 non-null      object
 3   market      6 non-null      object
 4   price       6 non-null      int64
 5   volume      6 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 416.0+ bytes
Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

=============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        8 non-null      datetime64[ns]
 1   id          8 non-null      object
 2   stock_name  8 non-null      object
 3   market      8 non-null      object
 4   price       8 non-null      int64
 5   volume      8 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 512.0+ bytes
Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

In [47]:
## ==============================================================
## 동일한 컬럼 구조 
## 컬럼 : 'date', 'id', 'stock_name', 'market', 'price', 'volume'
## 3개 DF 연결
## ==============================================================

[2] DataFrame 연결 - 동일 인덱스의 행 <hr>

In [54]:
## -----------------------------------
## [2-1] axis=0 : 위아래 방향으로 연결
## -----------------------------------
resultDF = pd.concat( [janDF, febDF, marDF], 
                      axis=0 )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 18개
열 개수     : 6개
행 인덱스   : Index([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype='int64')
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

        date    id stock_name market   price    volume
0 2024-01-02  A001       삼성전자  KOSPI   78500  15680000
1 2024-01-02  A002     SK하이닉스  KOSPI  141500   5120000
2 2024-01-02  A003      NAVER  KOSPI  226000    690000
3 2024-01-03  A001       삼성전자  KOSPI   77000  13250000
4 2024-01-03  A002     SK하이닉스  KOSPI  139000   4830000
5 2024-01-03  A003      NAVER  KOSPI  223500    580000
0 2024-02-01  A001       삼성전자  KOSPI   75200  11800000
1 2024-02-01  A002     SK하이닉스  KOSPI  133000   4320000
2 2024-02-01  A003      NAVER  KOSPI  216500    520000
3 2024-02-02  A001       삼성전자  KOSPI   75900  12150000
4 2024-02-02  A002     SK하이닉스  KOSPI  136000   4670000
5 2024-02-02  A003      NAVER  KOSPI  218000    610000
0 2024-03-04  A001       삼성전자  KOSPI   78000  14200000
1 2024-03-04  A002     SK하이닉스  KOSPI  159000   6450000
2 2024-03-04  A003      NAVER  KOSPI  205000    770000
3 2024-03-05  A001       삼성전자  KOSPI   78500  13850000
4 2024-03-05  A002     SK하이닉스  KOSPI  161500   6830000
5 2024-03-05  A003      NAVER  KOSPI  207000    810000

In [49]:
## 3개 DF의 행 인덱스 정리 필요 : ignore_index=True
resultDF = pd.concat(  [janDF, febDF, marDF], 
                       axis=0,
                       ignore_index=True )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 18개
열 개수     : 6개
행 인덱스   : RangeIndex(start=0, stop=18, step=1)
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

         date    id stock_name market   price    volume
0  2024-01-02  A001       삼성전자  KOSPI   78500  15680000
1  2024-01-02  A002     SK하이닉스  KOSPI  141500   5120000
2  2024-01-02  A003      NAVER  KOSPI  226000    690000
3  2024-01-03  A001       삼성전자  KOSPI   77000  13250000
4  2024-01-03  A002     SK하이닉스  KOSPI  139000   4830000
5  2024-01-03  A003      NAVER  KOSPI  223500    580000
6  2024-02-01  A001       삼성전자  KOSPI   75200  11800000
7  2024-02-01  A002     SK하이닉스  KOSPI  133000   4320000
8  2024-02-01  A003      NAVER  KOSPI  216500    520000
9  2024-02-02  A001       삼성전자  KOSPI   75900  12150000
10 2024-02-02  A002     SK하이닉스  KOSPI  136000   4670000
11 2024-02-02  A003      NAVER  KOSPI  218000    610000
12 2024-03-04  A001       삼성전자  KOSPI   78000  14200000
13 2024-03-04  A002     SK하이닉스  KOSPI  159000   6450000
14 2024-03-04  A003      NAVER  KOSPI  205000    770000
15 2024-03-05  A001       삼성전자  KOSPI   78500  13850000
16 2024-03-05  A002     SK하이닉스  KOSPI  161500   6830000
17 2024-03-05  A003      NAVER  KOSPI  207000    810000

In [50]:
## keys 사용하여 중복 행 인덱스 식별 
## ==> MultiIndex Index 형태가 됨!
resultDF = pd.concat( [janDF, febDF, marDF], 
                      axis=0,
                      keys=["2024_01", "2024_02", "2024_03"] )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 18개
열 개수     : 6개
행 인덱스   : MultiIndex([('2024_01', 0),
            ('2024_01', 1),
            ('2024_01', 2),
            ('2024_01', 3),
            ('2024_01', 4),
            ('2024_01', 5),
            ('2024_02', 0),
            ('2024_02', 1),
            ('2024_02', 2),
            ('2024_02', 3),
            ('2024_02', 4),
            ('2024_02', 5),
            ('2024_03', 0),
            ('2024_03', 1),
            ('2024_03', 2),
            ('2024_03', 3),
            ('2024_03', 4),
            ('2024_03', 5)],
           )
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

                date    id stock_name market   price    volume
2024_01 0 2024-01-02  A001       삼성전자  KOSPI   78500  15680000
        1 2024-01-02  A002     SK하이닉스  KOSPI  141500   5120000
        2 2024-01-02  A003      NAVER  KOSPI  226000    690000
        3 2024-01-03  A001       삼성전자  KOSPI   77000  13250000
        4 2024-01-03  A002     SK하이닉스  KOSPI  139000   4830000
        5 2024-01-03  A003      NAVER  KOSPI  223500    580000
2024_02 0 2024-02-01  A001       삼성전자  KOSPI   75200  11800000
        1 2024-02-01  A002     SK하이닉스  KOSPI  133000   4320000
        2 2024-02-01  A003      NAVER  KOSPI  216500    520000
        3 2024-02-02  A001       삼성전자  KOSPI   75900  12150000
        4 2024-02-02  A002     SK하이닉스  KOSPI  136000   4670000
        5 2024-02-02  A003      NAVER  KOSPI  218000    610000
2024_03 0 2024-03-04  A001       삼성전자  KOSPI   78000  14200000
        1 2024-03-04  A002     SK하이닉스  KOSPI  159000   6450000
        2 2024-03-04  A003      NAVER  KOSPI  205000    770000
        3 2024-03-05  A001       삼성전자  KOSPI   78500  13850000
        4 2024-03-05  A002     SK하이닉스  KOSPI  161500   6830000
        5 2024-03-05  A003      NAVER  KOSPI  207000    810000

In [51]:
## -----------------------------------
## [2-2] axis=1 : 좌우 방향으로 연결
## -----------------------------------
## 컬럼명 중복 발생!!!
resultDF = pd.concat( [janDF, febDF, marDF], 
                      axis=1 )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 6개
열 개수     : 18개
행 인덱스   : RangeIndex(start=0, stop=6, step=1)
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume', 'date', 'id',
       'stock_name', 'market', 'price', 'volume', 'date', 'id', 'stock_name',
       'market', 'price', 'volume'],
      dtype='object')

,date,id,stock_name,market,price,volume,date,id,stock_name,market,price,volume,date,id,stock_name,market,price,volume
0,2024-01-02,A001,삼성전자,KOSPI,78500,15680000,2024-02-01,A001,삼성전자,KOSPI,75200,11800000,2024-03-04,A001,삼성전자,KOSPI,78000,14200000
1,2024-01-02,A002,SK하이닉스,KOSPI,141500,5120000,2024-02-01,A002,SK하이닉스,KOSPI,133000,4320000,2024-03-04,A002,SK하이닉스,KOSPI,159000,6450000
2,2024-01-02,A003,NAVER,KOSPI,226000,690000,2024-02-01,A003,NAVER,KOSPI,216500,520000,2024-03-04,A003,NAVER,KOSPI,205000,770000
3,2024-01-03,A001,삼성전자,KOSPI,77000,13250000,2024-02-02,A001,삼성전자,KOSPI,75900,12150000,2024-03-05,A001,삼성전자,KOSPI,78500,13850000
4,2024-01-03,A002,SK하이닉스,KOSPI,139000,4830000,2024-02-02,A002,SK하이닉스,KOSPI,136000,4670000,2024-03-05,A002,SK하이닉스,KOSPI,161500,6830000
5,2024-01-03,A003,NAVER,KOSPI,223500,580000,2024-02-02,A003,NAVER,KOSPI,218000,610000,2024-03-05,A003,NAVER,KOSPI,207000,810000

In [52]:
## keys : 사용하면 어느 파일에서 온 컬럼인지 구분
## ==> MultiIndex Column 형태가 됨!
resultDF = pd.concat( [janDF, febDF, marDF], 
                      axis=1,
                      keys=["2024_01", "2024_02", "2024_03"] )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 6개
열 개수     : 18개
행 인덱스   : RangeIndex(start=0, stop=6, step=1)
열 인덱스   : MultiIndex([('2024_01',       'date'),
            ('2024_01',         'id'),
            ('2024_01', 'stock_name'),
            ('2024_01',     'market'),
            ('2024_01',      'price'),
            ('2024_01',     'volume'),
            ('2024_02',       'date'),
            ('2024_02',         'id'),
            ('2024_02', 'stock_name'),
            ('2024_02',     'market'),
            ('2024_02',      'price'),
            ('2024_02',     'volume'),
            ('2024_03',       'date'),
            ('2024_03',         'id'),
            ('2024_03', 'stock_name'),
            ('2024_03',     'market'),
            ('2024_03',      'price'),
            ('2024_03',     'volume')],
           )

     2024_01                                              2024_02        \
        date    id stock_name market   price    volume       date    id
0 2024-01-02  A001       삼성전자  KOSPI   78500  15680000 2024-02-01  A001
1 2024-01-02  A002     SK하이닉스  KOSPI  141500   5120000 2024-02-01  A002
2 2024-01-02  A003      NAVER  KOSPI  226000    690000 2024-02-01  A003
3 2024-01-03  A001       삼성전자  KOSPI   77000  13250000 2024-02-02  A001
4 2024-01-03  A002     SK하이닉스  KOSPI  139000   4830000 2024-02-02  A002
5 2024-01-03  A003      NAVER  KOSPI  223500    580000 2024-02-02  A003

                                         2024_03                          \
  stock_name market   price    volume       date    id stock_name market
0       삼성전자  KOSPI   75200  11800000 2024-03-04  A001       삼성전자  KOSPI
1     SK하이닉스  KOSPI  133000   4320000 2024-03-04  A002     SK하이닉스  KOSPI
2      NAVER  KOSPI  216500    520000 2024-03-04  A003      NAVER  KOSPI
3       삼성전자  KOSPI   75900  12150000 2024-03-05  A001       삼성전자  KOSPI
4     SK하이닉스  KOSPI  136000   4670000 2024-03-05  A002     SK하이닉스  KOSPI
5      NAVER  KOSPI  218000    610000 2024-03-05  A003      NAVER  KOSPI


    price    volume
0   78000  14200000
1  159000   6450000
2  205000    770000
3   78500  13850000
4  161500   6830000
5  207000    810000

[3] 행 인덱스 다른 DataFrame 연결 <hr>

In [55]:
## -----------------------------------
## [3-1] axis=0 : 위아래 방향으로 연결. 행 인덱스 다름
## -----------------------------------
resultDF = pd.concat( [janDF, apiDF], 
                      axis=0 )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 14개
열 개수     : 6개
행 인덱스   : Index([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7], dtype='int64')
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume'], dtype='object')

        date    id stock_name market   price    volume
0 2024-01-02  A001       삼성전자  KOSPI   78500  15680000
1 2024-01-02  A002     SK하이닉스  KOSPI  141500   5120000
2 2024-01-02  A003      NAVER  KOSPI  226000    690000
3 2024-01-03  A001       삼성전자  KOSPI   77000  13250000
4 2024-01-03  A002     SK하이닉스  KOSPI  139000   4830000
5 2024-01-03  A003      NAVER  KOSPI  223500    580000
0 2024-04-04  A001       삼성전자  KOSPI   78000  14200000
1 2024-04-04  A002     SK하이닉스  KOSPI  159000   6450000
2 2024-04-04  A003      NAVER  KOSPI  205000    770000
3 2024-04-05  A001       삼성전자  KOSPI   78500  13850000
4 2024-04-05  A002     SK하이닉스  KOSPI  161500   6830000
5 2024-04-05  A003      NAVER  KOSPI  207000    810000
6 2024-04-06  A001       삼성전자  KOSPI   78500  13850000
7 2024-04-06  A002     SK하이닉스  KOSPI  161500   6830000

In [ ]:
## -----------------------------------
## [3-2] axis=1 : 좌우 방향으로 연결. 행 인덱스 다름 => NAN발생
## -----------------------------------
## 모든 행 연결 : join='outer' [기]
resultDF = pd.concat( [janDF, apiDF], 
                      axis=1 )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 8개
열 개수     : 12개
행 인덱스   : RangeIndex(start=0, stop=8, step=1)
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume', 'date', 'id',
       'stock_name', 'market', 'price', 'volume'],
      dtype='object')

,date,id,stock_name,market,price,volume,date,id,stock_name,market,price,volume
0,2024-01-02,A001,삼성전자,KOSPI,78500.0,15680000.0,2024-04-04,A001,삼성전자,KOSPI,78000,14200000
1,2024-01-02,A002,SK하이닉스,KOSPI,141500.0,5120000.0,2024-04-04,A002,SK하이닉스,KOSPI,159000,6450000
2,2024-01-02,A003,NAVER,KOSPI,226000.0,690000.0,2024-04-04,A003,NAVER,KOSPI,205000,770000
3,2024-01-03,A001,삼성전자,KOSPI,77000.0,13250000.0,2024-04-05,A001,삼성전자,KOSPI,78500,13850000
4,2024-01-03,A002,SK하이닉스,KOSPI,139000.0,4830000.0,2024-04-05,A002,SK하이닉스,KOSPI,161500,6830000
5,2024-01-03,A003,NAVER,KOSPI,223500.0,580000.0,2024-04-05,A003,NAVER,KOSPI,207000,810000
6,NaT,NaN,NaN,NaN,NaN,NaN,2024-04-06,A001,삼성전자,KOSPI,78500,13850000
7,NaT,NaN,NaN,NaN,NaN,NaN,2024-04-06,A002,SK하이닉스,KOSPI,161500,6830000

In [57]:
## -----------------------------------
## [3-3] axis=1 : 좌우 방향으로 연결. 행 인덱스 다름 => NAN발생
## -----------------------------------
## 모두 존재하는 행 인덱스만 연결 : join='inner'
resultDF = pd.concat( [janDF, apiDF], 
                      axis=1,
                      join='inner' )

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 6개
열 개수     : 12개
행 인덱스   : RangeIndex(start=0, stop=6, step=1)
열 인덱스   : Index(['date', 'id', 'stock_name', 'market', 'price', 'volume', 'date', 'id',
       'stock_name', 'market', 'price', 'volume'],
      dtype='object')

,date,id,stock_name,market,price,volume,date,id,stock_name,market,price,volume
0,2024-01-02,A001,삼성전자,KOSPI,78500,15680000,2024-04-04,A001,삼성전자,KOSPI,78000,14200000
1,2024-01-02,A002,SK하이닉스,KOSPI,141500,5120000,2024-04-04,A002,SK하이닉스,KOSPI,159000,6450000
2,2024-01-02,A003,NAVER,KOSPI,226000,690000,2024-04-04,A003,NAVER,KOSPI,205000,770000
3,2024-01-03,A001,삼성전자,KOSPI,77000,13250000,2024-04-05,A001,삼성전자,KOSPI,78500,13850000
4,2024-01-03,A002,SK하이닉스,KOSPI,139000,4830000,2024-04-05,A002,SK하이닉스,KOSPI,161500,6830000
5,2024-01-03,A003,NAVER,KOSPI,223500,580000,2024-04-05,A003,NAVER,KOSPI,207000,810000