#### 【 그룹화 / 그룹연산 】<hr>
- 특정 값을 기준으로 데이터 묶음 후 그룹화
- 그룹별 연산 진행
- 데이터 집계/변환/필터링에 효과적

In [62]:
## 모듈 로딩
import pandas as pd

In [63]:
## DataFrame 인스턴스 생성
df = pd.DataFrame({ '지점': ['서울','서울','서울','부산','부산','대구','대구','대구'],
                    '상품': ['A','A','B','A','B','A','B','B'],
                    '매출': [100,150,200,120,180,90,210,240],
                    '수량': [10,15,20,12,18,9,21,24] })
## 구조 확인
display(df)

   지점 상품   매출  수량
0  서울  A  100  10
1  서울  A  150  15
2  서울  B  200  20
3  부산  A  120  12
4  부산  B  180  18
5  대구  A   90   9
6  대구  B  210  21
7  대구  B  240  24

[1] 그룹화 <hr>

In [64]:
## ----------------------------------------
## 단일 컬럼 그룹화
## ----------------------------------------
## 지점별 그룹화 
g = df.groupby('지점')

## 그룹 속성 확인
print( f"-> 그룹수 : { g.ngroups}개" )           # 그룹 수
print( f"-> 그룹별 : {g.groups}"  )              # 각 그룹의 인덱스
print( f"-> 그룹별 행 수\n{g.size()}" )           # 그룹별 행 수

-> 그룹수 : 3개
-> 그룹별 : {'대구': [5, 6, 7], '부산': [3, 4], '서울': [0, 1, 2]}
-> 그룹별 행 수
지점
대구    3
부산    2
서울    3
dtype: int64

In [65]:
## 그룹별 데이터 추출
for k in g.groups.keys():
    print(f'\n[{k}]=====')
    print(g.get_group(k))

[대구]=====
   지점 상품   매출  수량
5  대구  A   90   9
6  대구  B  210  21
7  대구  B  240  24

[부산]=====
   지점 상품   매출  수량
3  부산  A  120  12
4  부산  B  180  18

[서울]=====
   지점 상품   매출  수량
0  서울  A  100  10
1  서울  A  150  15
2  서울  B  200  20

[2] 그룹연산 - 기본 집계 메서드들 <hr>

In [66]:
## (1) 지점 그룹별 합계
display( g.sum(numeric_only=True))

     매출  수량
지점
대구  540  54
부산  300  30
서울  450  45

In [67]:
## (2) 지점 그룹별 평균
display( g.mean(numeric_only=True))

       매출    수량
지점
대구  180.0  18.0
부산  150.0  15.0
서울  150.0  15.0

In [72]:
## (3) 지점 그룹별 여러 집계 동시 적용
g[['매출','수량']].agg(['sum','mean'])

     매출         수량
    sum   mean sum  mean
지점
대구  540  180.0  54  18.0
부산  300  150.0  30  15.0
서울  450  150.0  45  15.0

In [73]:
## (4) 지점 그룹별 여러 집계 다르게 적용
display( g.agg( {'매출':['sum','mean'], '수량':['max','min']} ) )

     매출         수량
    sum   mean max min
지점
대구  540  180.0  24   9
부산  300  150.0  18  12
서울  450  150.0  20  10

In [ ]:
## (4)지점의 상품별 매출 합계와 평균 
## => 지점별 그룹화 결과에 다시 상품으로 그룹화
for key in g.groups.keys():
    print(f'\n[{key}]=====')
    localDF = g.get_group(key).drop(columns='지점').reset_index(drop=True)
   
    localDF=localDF.groupby('상품')
    display( localDF.agg({'매출':['sum','mean']}) )

[('대구', 'A')]=====

    매출
   sum  mean
상품
A   90  90.0

[('대구', 'B')]=====

     매출
    sum   mean
상품
B   450  225.0

[('부산', 'A')]=====

     매출
    sum   mean
상품
A   120  120.0

[('부산', 'B')]=====

     매출
    sum   mean
상품
B   180  180.0

[('서울', 'A')]=====

     매출
    sum   mean
상품
A   250  125.0

[('서울', 'B')]=====

     매출
    sum   mean
상품
B   200  200.0

In [53]:
## ----------------------------------------
## 다중 컬럼 그룹화
## ----------------------------------------

## ==> 지점별 상품에 따른 매출 합계와 평균 집계 
g = df.groupby(['지점','상품'])

## 그룹별 데이터 추출
for k in g.groups.keys():
    print(f'\n[{k}]=====')
    print(g.get_group(k))

[('대구', 'A')]=====
   지점 상품  매출  수량
5  대구  A  90   9

[('대구', 'B')]=====
   지점 상품   매출  수량
6  대구  B  210  21
7  대구  B  240  24

[('부산', 'A')]=====
   지점 상품   매출  수량
3  부산  A  120  12

[('부산', 'B')]=====
   지점 상품   매출  수량
4  부산  B  180  18

[('서울', 'A')]=====
   지점 상품   매출  수량
0  서울  A  100  10
1  서울  A  150  15

[('서울', 'B')]=====
   지점 상품   매출  수량
2  서울  B  200  20

In [54]:
## 지점별 상품에 따른 매출 합계와 평균 집계 
g.agg(['sum','mean'])

        매출         수량
       sum   mean sum  mean
지점 상품
대구 A    90   90.0   9   9.0
   B   450  225.0  45  22.5
부산 A   120  120.0  12  12.0
   B   180  180.0  18  18.0
서울 A   250  125.0  25  12.5
   B   200  200.0  20  20.0

In [57]:
## -------------------------------------
## agg와 transform 메서드의 차이
## agg()        : 그룹별 결과 출력
## transform () : 행별 결과 출력
## -------------------------------------
g.agg(['sum'])

        매출  수량
       sum sum
지점 상품
대구 A    90   9
   B   450  45
부산 A   120  12
   B   180  18
서울 A   250  25
   B   200  20

In [58]:
g.transform('sum')

    매출  수량
0  250  25
1  250  25
2  200  20
3  120  12
4  180  18
5   90   9
6  450  45
7  450  45

[3] agg() / transform() 과 lambda <hr>

In [29]:
## DataFrame 인스턴스 생성
df = pd.DataFrame({ '지점': ['서울','서울','서울','부산','부산','부산','대구','대구','대구'],
                    '매출': [100,150,200,120,180,160,90,210,240] })
## 확인
display(df)

   지점   매출
0  서울  100
1  서울  150
2  서울  200
3  부산  120
4  부산  180
5  부산  160
6  대구   90
7  대구  210
8  대구  240

In [ ]:
## ------------------------------------------
## (1) 그룹별 평균 매출 대비 비율
## ------------------------------------------
df['매출비율'] = df.groupby('지점')['매출'].transform(lambda x: x / x.mean())

## 같은 지점 내에서 매출이 
## 평균보다 높은지/낮은지 한눈에 파악
display(df)

## 지점별로 매출의 범위(최대값 - 최소값)를 계산
# lambda x에서 x는 각 지점별 '매출' 시리즈(Series)를 의미
branch_range = df.groupby('지점')['매출'].agg(lambda x: x.max() - x.min())
print("지점별 매출 변동 폭:")
display(branch_range)

   지점 상품   매출  수량      매출비율
0  서울  A  100  10  0.666667
1  서울  A  150  15  1.000000
2  서울  B  200  20  1.333333
3  부산  A  120  12  0.800000
4  부산  B  180  18  1.200000
5  대구  A   90   9  0.500000
6  대구  B  210  21  1.166667
7  대구  B  240  24  1.333333

지점별 매출 변동 폭:

지점
대구    150
부산     60
서울    100
Name: 매출, dtype: int64

In [60]:
df['표준화'] = df.groupby('지점')['매출'].transform(lambda x: (x - x.mean()) / x.std())
display(df)

   지점 상품   매출  수량      매출비율       표준화
0  서울  A  100  10  0.666667 -1.000000
1  서울  A  150  15  1.000000  0.000000
2  서울  B  200  20  1.333333  1.000000
3  부산  A  120  12  0.800000 -0.707107
4  부산  B  180  18  1.200000  0.707107
5  대구  A   90   9  0.500000 -1.133893
6  대구  B  210  21  1.166667  0.377964
7  대구  B  240  24  1.333333  0.755929

In [61]:
df['순위'] = df.groupby('지점')['매출'].transform(lambda x: x.rank(ascending=False))
display(df)

   지점 상품   매출  수량      매출비율       표준화   순위
0  서울  A  100  10  0.666667 -1.000000  3.0
1  서울  A  150  15  1.000000  0.000000  2.0
2  서울  B  200  20  1.333333  1.000000  1.0
3  부산  A  120  12  0.800000 -0.707107  2.0
4  부산  B  180  18  1.200000  0.707107  1.0
5  대구  A   90   9  0.500000 -1.133893  3.0
6  대구  B  210  21  1.166667  0.377964  2.0
7  대구  B  240  24  1.333333  0.755929  1.0