#### 【 데이터 병합 】<hr>
- 목적 : 공통 컬럼 값을 기준으로 관련 있는 행끼리 찾아서 연결하는 함수

- 기준 : 특정 컬럼 값

- 사용 : 서로 다른 정보를 공통 기준으로 연결할 경우

- 메서드 : pandas.merge()
    * 주요 매개변수 : on, how

[1] 모듈 로딩 및 데이터 준비 <hr>

In [22]:
## 모듈 로딩
import pandas as pd

In [23]:
## 데이터 파일들
FILE1 = '../DATA/stock price.xlsx'
FILE2 = '../DATA/stock valuation.xlsx'

[2] 데이터 로딩 및 기본 정보 확인<hr>

In [24]:
## -----------------------------------
## 데이터 로딩 : 첫번째 행 - 컬럼명 OK
## -----------------------------------
priceDF = pd.read_excel(FILE1)
valuaDF = pd.read_excel(FILE2)

In [25]:
## -----------------------------------
## 기본 정보 확인
## -----------------------------------
df_list = [priceDF, valuaDF]

for df in df_list:
    print(f'\n=============')
    df.info()
    print(df.columns)

=============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   stock_name  10 non-null     object
 2   value       10 non-null     float64
 3   price       10 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 448.0+ bytes
Index(['id', 'stock_name', 'value', 'price'], dtype='object')

=============
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     object
 2   eps     10 non-null     float64
 3   bps     10 non-null     int64
 4   per     10 non-null     float64
 5   pbr     10 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 608.0+ bytes
Index(['id', 'name', 'eps', 'bps', 'per', 'pbr'], dtype='object')

In [26]:
## ==============================================================
## 서로 다른 구조
## stock price.xlsx     컬럼: id, stock_name, value, price
## stock valuation.xlsx 컬럼: id, name, eps, bps, per, pbr
## 공통 컬럼             id
## ==============================================================

[2] id 기준으로 두 파일 연결 <hr>

In [27]:
## -----------------------------------
## [2-1] on='id'     : id 값이 양쪽 파일에 모두 있는 데이터만 연결
##       how='inner' : 2개 DF 공통 id 
## -----------------------------------
resultDF = pd.merge(priceDF, valuaDF, on='id', how='inner')

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 5개
열 개수     : 9개
행 인덱스   : RangeIndex(start=0, stop=5, step=1)
열 인덱스   : Index(['id', 'stock_name', 'value', 'price', 'name', 'eps', 'bps', 'per',
       'pbr'],
      dtype='object')

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,이마트,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,종근당,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [28]:
## 동일 내용, 다른 컬럼명 정리 :  stock_name, name 
resultDF = pd.merge(priceDF, valuaDF, on='id', how='inner')
resultDF = resultDF.drop(columns="name")

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 5개
열 개수     : 8개
행 인덱스   : RangeIndex(start=0, stop=5, step=1)
열 인덱스   : Index(['id', 'stock_name', 'value', 'price', 'eps', 'bps', 'per', 'pbr'], dtype='object')

,id,stock_name,value,price,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,85.166667,5335,40.802348,0.651359

In [29]:
## -----------------------------------
## [2-2] how ='left' : 왼쪽 파일 기준으로 연결
## -----------------------------------
## => 왼쪽에 행 모두 출력 => 오른쪽 존재하지 않는 값 NaN
resultDF = pd.merge(priceDF, valuaDF, on='id', how='left')

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 10개
열 개수     : 9개
행 인덱스   : RangeIndex(start=0, stop=10, step=1)
열 인덱스   : Index(['id', 'stock_name', 'value', 'price', 'name', 'eps', 'bps', 'per',
       'pbr'],
      dtype='object')

,id,stock_name,value,price,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,138250,엔에스쇼핑,14558.666667,13200,NaN,NaN,NaN,NaN,NaN
3,139480,이마트,239230.833333,254500,이마트,18268.166667,295780.0,13.931338,0.860437
4,142280,녹십자엠에스,468.833333,10200,NaN,NaN,NaN,NaN,NaN
5,145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090.0,14.283226,0.758627
6,185750,종근당,40293.666667,100500,종근당,3990.333333,40684.0,25.185866,2.470259
7,192400,쿠쿠홀딩스,179204.666667,177500,NaN,NaN,NaN,NaN,NaN
8,199800,툴젠,-2514.333333,115400,NaN,NaN,NaN,NaN,NaN
9,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335.0,40.802348,0.651359

In [30]:
## -----------------------------------
## [2-3] how ='right' : 왼쪽 파일 기준으로 연결
## -----------------------------------
## => 오른쪽에 행 모두 출력 => 왼쪽 존재하지 않는 값 NaN
resultDF = pd.merge(priceDF, valuaDF, on='id', how='right')

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 10개
열 개수     : 9개
행 인덱스   : RangeIndex(start=0, stop=10, step=1)
열 인덱스   : Index(['id', 'stock_name', 'value', 'price', 'name', 'eps', 'bps', 'per',
       'pbr'],
      dtype='object')

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900.0,CJ E&M,6301.333333,54068,15.695091,1.829178
1,136480,NaN,NaN,NaN,하림,274.166667,3551,11.489362,0.887074
2,138040,NaN,NaN,NaN,메리츠금융지주,2122.333333,14894,6.313806,0.899691
3,139480,이마트,239230.833333,254500.0,이마트,18268.166667,295780,13.931338,0.860437
4,145990,삼양사,82750.000000,82000.0,삼양사,5741.000000,108090,14.283226,0.758627
5,161390,NaN,NaN,NaN,한국타이어,5648.500000,51341,7.453306,0.820007
6,181710,NaN,NaN,NaN,NHN엔터테인먼트,2110.166667,78434,30.755864,0.827447
7,185750,종근당,40293.666667,100500.0,종근당,3990.333333,40684,25.185866,2.470259
8,204210,모두투어리츠,3093.333333,3475.0,모두투어리츠,85.166667,5335,40.802348,0.651359
9,207940,NaN,NaN,NaN,삼성바이오로직스,4644.166667,60099,89.790059,6.938551

In [31]:
## -----------------------------------
## [2-4] how ='outer' : 양쪽 파일 기준으로 연결
## -----------------------------------
## => 오른쪽/왼쪽 행 모두 출력 => 존재하지 않는 값 NaN
resultDF = pd.merge(priceDF, valuaDF, on='id', how='outer')

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 15개
열 개수     : 9개
행 인덱스   : RangeIndex(start=0, stop=15, step=1)
열 인덱스   : Index(['id', 'stock_name', 'value', 'price', 'name', 'eps', 'bps', 'per',
       'pbr'],
      dtype='object')

,id,stock_name,value,price,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000.0,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900.0,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,136480,NaN,NaN,NaN,하림,274.166667,3551.0,11.489362,0.887074
3,138040,NaN,NaN,NaN,메리츠금융지주,2122.333333,14894.0,6.313806,0.899691
4,138250,엔에스쇼핑,14558.666667,13200.0,NaN,NaN,NaN,NaN,NaN
5,139480,이마트,239230.833333,254500.0,이마트,18268.166667,295780.0,13.931338,0.860437
6,142280,녹십자엠에스,468.833333,10200.0,NaN,NaN,NaN,NaN,NaN
7,145990,삼양사,82750.000000,82000.0,삼양사,5741.000000,108090.0,14.283226,0.758627
8,161390,NaN,NaN,NaN,한국타이어,5648.500000,51341.0,7.453306,0.820007
9,181710,NaN,NaN,NaN,NHN엔터테인먼트,2110.166667,78434.0,30.755864,0.827447
10,185750,종근당,40293.666667,100500.0,종근당,3990.333333,40684.0,25.185866,2.470259
11,192400,쿠쿠홀딩스,179204.666667,177500.0,NaN,NaN,NaN,NaN,NaN
12,199800,툴젠,-2514.333333,115400.0,NaN,NaN,NaN,NaN,NaN
13,204210,모두투어리츠,3093.333333,3475.0,모두투어리츠,85.166667,5335.0,40.802348,0.651359
14,207940,NaN,NaN,NaN,삼성바이오로직스,4644.166667,60099.0,89.790059,6.938551

[3] 특정 컬럼 기준으로 연결<hr>

In [33]:
## -----------------------------------
## [3-1] 특정 컬럼까지 같이 기준으로 연결하고 싶은 경우
## -----------------------------------
## 회사명 컬럼 기준으로 연결
valuaDF = valuaDF.rename(columns={"name": "stock_name"})

resultDF = pd.merge(priceDF, valuaDF, on='stock_name')

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 5개
열 개수     : 9개
행 인덱스   : RangeIndex(start=0, stop=5, step=1)
열 인덱스   : Index(['id_x', 'stock_name', 'value', 'price', 'id_y', 'eps', 'bps', 'per',
       'pbr'],
      dtype='object')

,id_x,stock_name,value,price,id_y,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,130960,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,139480,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,145990,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,185750,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,204210,85.166667,5335,40.802348,0.651359

In [34]:
## -----------------------------------
## [3-2] 2개 컬럼 기준으로 연결하고 싶은 경우
## -----------------------------------
## id, 회사명 컬럼 기준으로 연결
resultDF = pd.merge(priceDF, valuaDF, on=['id','stock_name'])

print(f"행 개수     : {resultDF.shape[0] }개")
print(f"열 개수     : {resultDF.shape[1] }개")
print(f"행 인덱스   : {resultDF.index }")
print(f"열 인덱스   : {resultDF.columns }")
display(resultDF)

행 개수     : 5개
열 개수     : 8개
행 인덱스   : RangeIndex(start=0, stop=5, step=1)
열 인덱스   : Index(['id', 'stock_name', 'value', 'price', 'eps', 'bps', 'per', 'pbr'], dtype='object')

,id,stock_name,value,price,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,85.166667,5335,40.802348,0.651359